### ISSUE TITLE
Add Gunicorn to requirements.txt

### ISSUE THREAD

**Issue by BlueskyFR** [Reachip/ade-usmb-api-unofficial#1]
Heyy :)

I don't do a lot of Python but I guess Gunicorn has to be added to the requirements.txt file :)
Nice work you're doing here, at the Ensimag we also have ADE and I did a similar work in parsing it for a Twitter bot tweeting after each math course :3

GL on your project!

**Comment by Reachip** [comment]
Thanks a lot !

The dependencie is on the line 9 on the requirement file : https://github.com/Reachip/ade-usmb-api-unofficial/blob/develop/requirements#L9

I don't like to precise the .txt extension for that, I don't have to do that in a unix systems.
